TXTIN=${SAMPDIR}/Sample_${SAMPLE}/${POP}.5M.imputed.dose.biallelic.recode.allelecount.txt
POSITS=${GENDIR}/${POP}/${POP}.5M.imputed.dose.biallelic.recode.posits.vcf.gz
TXTOUT=${ASEDIR}/${SAMPLE}_ASEReadCounter.merge.txt.gz

# convert CSV to VCF to CSV
bsub -o ${LOGDIR}/ETSB035_allelecounter.log -e ${ERRDIR}/ETSB035_allelecounter.err bash allelecount_allposits.sh ${SAMPDIR}/Sample_ETSB035/sabue.5M.imputed.dose.biallelic.recode.allelecount.txt ${GENDIR}/sabue/sabue.5M.imputed.dose.biallelic.recode.posits.vcf.gz ${RASQDIR}/sabue/allelecounter_out/ETSB035_ASEReadCounter.merge.txt.gz
bsub -o ${LOGDIR}/ETMS033_allelecounter.log -e ${ERRDIR}/ETMS033_allelecounter.err bash allelecount_allposits.sh ${SAMPDIR}/Sample_ETMS033/mursi.5M.imputed.dose.biallelic.recode.allelecount.txt ${GENDIR}/mursi/mursi.5M.imputed.dose.biallelic.recode.posits.vcf.gz ${RASQDIR}/mursi/allelecounter_out/ETMS033_ASEReadCounter.merge.txt.gz
bsub -o ${LOGDIR}/ETMS018_allelecounter.log -e ${ERRDIR}/ETMS018_allelecounter.err bash allelecount_allposits.sh ${SAMPDIR}/Sample_ETMS018/mursi.5M.imputed.dose.biallelic.recode.allelecount.txt ${GENDIR}/mursi/mursi.5M.imputed.dose.biallelic.recode.posits.vcf.gz ${RASQDIR}/mursi/allelecounter_out/ETMS018_ASEReadCounter.merge.txt.gz
bsub -o ${LOGDIR}/ETDI002_allelecounter.log -e ${ERRDIR}/ETDI002_allelecounter.err bash allelecount_allposits.sh ${SAMPDIR}/Sample_ETDI002/dizi.5M.imputed.dose.biallelic.recode.allelecount.txt ${GENDIR}/dizi/dizi.5M.imputed.dose.biallelic.recode.posits.vcf.gz ${RASQDIR}/dizi/allelecounter_out/ETDI002_ASEReadCounter.merge.txt.gz
bsub -o ${LOGDIR}/ETAM055_allelecounter.log -e ${ERRDIR}/ETAM055_allelecounter.err bash allelecount_allposits.sh ${SAMPDIR}/Sample_ETAM055/amhara.5M.imputed.dose.biallelic.recode.allelecount.txt ${GENDIR}/amhara/amhara.5M.imputed.dose.biallelic.recode.posits.vcf.gz ${RASQDIR}/amhara/allelecounter_out/ETAM055_ASEReadCounter.merge.txt.gz
bsub -o ${LOGDIR}/ETAM051_allelecounter.log -e ${ERRDIR}/ETAM051_allelecounter.err bash allelecount_allposits.sh ${SAMPDIR}/Sample_ETAM051/amhara.5M.imputed.dose.biallelic.recode.allelecount.txt ${GENDIR}/amhara/amhara.5M.imputed.dose.biallelic.recode.posits.vcf.gz ${RASQDIR}/amhara/allelecounter_out/ETAM051_ASEReadCounter.merge.txt.gz
bsub -o ${LOGDIR}/ETAS031_allelecounter.log -e ${ERRDIR}/ETAS031_allelecounter.err bash allelecount_allposits.sh ${SAMPDIR}/Sample_ETAS031/agaw.5M.imputed.dose.biallelic.recode.allelecount.txt ${GENDIR}/agaw/agaw.5M.imputed.dose.biallelic.recode.posits.vcf.gz ${RASQDIR}/agaw/allelecounter_out/ETAS031_ASEReadCounter.merge.txt.gz
bsub -o ${LOGDIR}/ETAS034_allelecounter.log -e ${ERRDIR}/ETAS034_allelecounter.err bash allelecount_allposits.sh ${SAMPDIR}/Sample_ETAS034/agaw.5M.imputed.dose.biallelic.recode.allelecount.txt ${GENDIR}/agaw/agaw.5M.imputed.dose.biallelic.recode.posits.vcf.gz ${RASQDIR}/agaw/allelecounter_out/ETAS034_ASEReadCounter.merge.txt.gz
